### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by ssoonmi** [lhsteele/Organa#4]
- [x] when you nest routes, make sure that you include the wildcard for the table its nested under, e.g. `/api/projects/:project_id/lists`

### `lists`
- [x] if you're returning a single list from a project, you only need the `list_id`, so `/api/lists/:id`

Great job with your backend routes!

**Comment by ssoonmi** [comment]
### tasks
- [ ] you don't need to nest tasks under projects if you're already nesting it under lists because the project id can already be found through the list since a list belongs to a project.
